### ISSUE TITLE
Signals of specific wells depends on how they're accessed. Maybe

### ISSUE THREAD

**Issue by bcaller** [chenopodium/TorrentScout#3]
I get a different signal with:

`readDat(datpath, chipType="314", row=mask$row[wellid],col=mask$col[wellid])$signal[1,]`

and

`readDat(datpath, chipType="314")$signal[wellid,]`

So I don't know which is the correct signal for that well.
(mask is the result of `readBeadFindMask`)

**Comment by chenopodium** [comment]
Hi, could you please point me to the Java class? It has been a while since I worked on this and any more details would help :-).  (And do you have an examle for the wellid? )
Thanks, Chantal

**Comment by bcaller** [comment]
Sorry I'm an idiot, I meant to post this for torrentR. I have been playing with both. Ignore me.
